// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveAndRunArtifact(arg1:boolean,arg2:Array<number>,arg3:string):Promise<string>;
