// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteScriptInTerminal(arg1:string,arg2:string):Promise<void>;

export function GetScriptManifest():Promise<string>;

export function GetServerAddress():Promise<string>;

export function SetServerAddress(arg1:string):Promise<void>;
