// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteScript(arg1, arg2) {
  return window['go']['main']['App']['ExecuteScript'](arg1, arg2);
}

export function GetScriptManifest() {
  return window['go']['main']['App']['GetScriptManifest']();
}
